### ISSUE TITLE
Export to .sql file

### ISSUE THREAD

**Issue by BerkSpar** [Kovalski-rgb/SCLAQ#1]
## Description
Create all functions and helpers to export any string to SQL. It'll be used when program completes all cycle.

## Exemples
```cs
ExportHelper.export("Some text here...", "path/to/save");
```

**Comment by Kovalski-rgb** [comment]
Done on [#af133d9](https://github.com/Kovalski-rgb/SCLAQ/commit/af133d9ca7e0f2be2781000a7a9927fda368b419)
